// Generated by CoffeeScript 1.4.0
(function() {
  var $, StockPage,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  $ = Spine.$;

  StockPage = (function(_super) {

    __extends(StockPage, _super);

    StockPage.prototype["default"] = "info";

    StockPage.prototype.footerMenuItem = {
      name: "stock",
      text: "个股"
    };

    StockPage.prototype.stockID = "000001.SS";

    StockPage.prototype.homeID = "000001.SS";

    StockPage.prototype.controllers = {
      info: Stock.StockInfo,
      tech: Stock.StockTech,
      history: Stock.StockHistory
    };

    function StockPage() {
      var _this = this;
      StockPage.__super__.constructor.apply(this, arguments);
      this.registerPageEvent("getinfo", function(stockID) {
        _this.stockID = stockID;
        _this.slientActive(_this.info);
        return true;
      });
      this.registerPageEvent("compare", function(compares) {
        if (!compares || compares.length < 1) {
          return false;
        }
        _this.slientActive(_this.tech);
        _this.stockID = compares.pop();
        return true;
      });
    }

    StockPage.prototype.setStock = function(stock) {
      this.stockID = stock;
      return this.refresh();
    };

    StockPage.prototype.deQuickBarClick = function(e) {
      var node, stock;
      node = $(e.target);
      stock = node.attr("name");
      if (stock) {
        this.setStock(stock);
      }
      return false;
    };

    StockPage.prototype.deFetchStock = function(e) {
      var value;
      value = this.searchText.val().slice(0, 6);
      if (!Stock.Util.isValidStockID(value)) {
        return false;
      }
      this.setStock(value);
      return false;
    };

    StockPage.prototype.deGoHome = function(e) {
      this.setStock(this.homeID);
      return false;
    };

    return StockPage;

  })(Stock.StockBasePage);

  window.Stock["StockPage"] = StockPage;

}).call(this);
