// Generated by CoffeeScript 1.4.0
(function() {
  var $, StockInfo,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __slice = [].slice;

  $ = Spine.$;

  StockInfo = (function(_super) {

    __extends(StockInfo, _super);

    StockInfo.prototype.tmplId = "stockInfoTmpl";

    StockInfo.prototype.dataTmplId = "stockInfoDataTmpl";

    StockInfo.prototype.headerMenuItem = {
      name: "info",
      text: "基本信息"
    };

    StockInfo.prototype.events = {
      'click .form-inline button.stock-add-btn': 'deOpenAddStockModal',
      'click #addTagButton': 'deAddTag',
      'click #addStockButton': 'deAddStock'
    };

    StockInfo.prototype.elements = {
      'div[data-role=panel-data]': 'panelData',
      '.modal-body select': 'tagSelects',
      '.modal-body input[type=text]': 'newTagText',
      '.modal-body form': 'addStockForm',
      '.form-inline button.stock-add-btn': "openAddModalButton"
    };

    function StockInfo() {
      this.fetchData = __bind(this.fetchData, this);
      this.fetchFinished = __bind(this.fetchFinished, this);      StockInfo.__super__.constructor.apply(this, arguments);
      this["gstock"] = new Stock.GoogStock;
      this.gstock.bind('fetchFinished', this.fetchFinished);
    }

    StockInfo.prototype.fetchFinished = function(result) {
      var data;
      if (result.status === "succ") {
        data = result.list[0];
        data.chart = Stock.YahooStock.fetchLargeChart(this.page.stockID);
        return this.trigger("dataReady", data);
      }
    };

    StockInfo.prototype.render = function(data) {
      var color;
      this.panelData.html($("#" + this.dataTmplId).tmpl(data));
      if (data) {
        if (data.c.charAt(0) === '-') {
          color = "#468847";
        } else if (data.c.charAt(0) === '+') {
          color = "#FF0000";
        }
        if (color) {
          this.$("#updownCell").css("color", color);
        }
      }
      if (this.page.stockID === this.page.homeID) {
        return this.$(".form-inline button.stock-add-btn").attr('disabled', 'disabled');
      } else {
        return this.$(".form-inline button.stock-add-btn").removeAttr("disabled");
      }
    };

    StockInfo.prototype.fetchData = function() {
      var args;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return this.gstock.fetchStock(this.page.stockID);
    };

    StockInfo.prototype.activate = function() {
      StockInfo.__super__.activate.apply(this, arguments);
      return this.startRefreshTimer();
    };

    StockInfo.prototype.startRefreshTimer = function() {
      if (this.isActive()) {
        this.delay(this.startRefreshTimer, 60000);
        return this.refresh();
      }
    };

    StockInfo.prototype.updateTagSelects = function() {
      var data, record, records, _i, _len, _results;
      Stock.TagList.fetch();
      if (Stock.TagList.count() === 0) {
        Stock.TagList.create(Stock.TagList["default"]);
      }
      records = Stock.TagList.all();
      this.tagSelects.empty();
      _results = [];
      for (_i = 0, _len = records.length; _i < _len; _i++) {
        record = records[_i];
        data = {
          name: record.name,
          text: record.name
        };
        _results.push(this.tagSelects.append($("#selectItemTmpl").tmpl(data)));
      }
      return _results;
    };

    StockInfo.prototype.appendTagSelect = function(name) {
      var data;
      if (Stock.TagList.findByAttribute("name", name)) {
        return Stock.Util.openAlert(this.addStockForm, {
          type: "alert-error",
          body: "Tag已经存在"
        });
      } else {
        data = {
          name: name,
          text: name
        };
        Stock.TagList.create({
          name: name
        });
        this.tagSelects.prepend($("#selectItemTmpl").tmpl(data));
        return this.tagSelects.get(0).selectedIndex = 0;
      }
    };

    StockInfo.prototype.deOpenAddStockModal = function(e) {
      this.updateTagSelects();
      $('#addStockModal').modal();
      e.preventDefault();
      return false;
    };

    StockInfo.prototype.deAddTag = function(e) {
      var name;
      name = this.newTagText.val();
      if (!name) {
        Stock.Util.openAlert(this.addStockForm, {
          type: "alert-error",
          body: "名字不能为空"
        });
      } else {
        this.appendTagSelect(name);
      }
      e.preventDefault();
      return false;
    };

    StockInfo.prototype.deAddStock = function(e) {
      var item, tag,
        _this = this;
      tag = this.tagSelects.val();
      item = Stock.StockList.select(function(item) {
        return item["stock"] === _this.page.stockID && item["tag"] === tag;
      });
      if (item.length > 0) {
        Stock.Util.openAlert(this.addStockForm, {
          type: "alert-error",
          body: "股票已经存在"
        });
      } else {
        Stock.StockList.create({
          stock: this.page.stockID,
          tag: tag
        });
        $('#addStockModal').modal('hide');
      }
      e.preventDefault();
      return false;
    };

    return StockInfo;

  })(Stock.MixedPanel);

  window.Stock["StockInfo"] = StockInfo;

}).call(this);
