// Generated by CoffeeScript 1.4.0
(function() {
  var $, GoogStock,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  $ = Spine.$;

  GoogStock = (function(_super) {

    __extends(GoogStock, _super);

    function GoogStock() {
      this.fetchNewsCallback = __bind(this.fetchNewsCallback, this);

      this.fetchStockCallback = __bind(this.fetchStockCallback, this);
      return GoogStock.__super__.constructor.apply(this, arguments);
    }

    GoogStock.include(Spine.Events);

    GoogStock.canonical = function(stockID) {
      var id, prefix, site;
      if (stockID.lastIndexOf(':') !== -1) {
        return stockID;
      }
      if (stockID.length < 6) {
        return;
      }
      id = stockID.slice(0, 6);
      if (stockID.lastIndexOf('.') !== -1 && stockID.length === 9) {
        site = stockID.slice(7, 9).toLowerCase();
        if (site === "ss") {
          prefix = "SHA:";
        } else {
          prefix = "SHE:";
        }
      } else {
        if (stockID.charAt(0) === '6') {
          prefix = "SHA:";
        } else {
          prefix = "SHE:";
        }
      }
      return "" + prefix + id;
    };

    GoogStock.prototype.fetchStock = function(stockID) {
      var cnUrlTemplete,
        _this = this;
      stockID = this.constructor.canonical(stockID);
      cnUrlTemplete = "http://www.google.cn/finance/info?q=" + stockID + "&infotype=infoquoteall&oe=gb2312&callback=?";
      return $.getJSON(cnUrlTemplete, function(data) {
        return _this.fetchStockCallback(data);
      });
    };

    /*
    	[ { "id": "7521596" ,"t" : "000001" ,"e" : "SHA" ,
    	"l" : "2,105.62" ,"l_cur" : "￥2,105.62" ,
    	"s": "0" ,"ltt":"15:01" ,"lt" : "10月17日 15:01" ,
    	"c" : "+6.81" ,"cp" : "0.32" ,"ccol" : "chr" ,
    	"eo" : "" ,"delay": "" ,"op" : "2,104.28" ,"hi" : "2,113.16" ,
    	"lo" : "2,088.04" ,"vo" : "5987.41万" ,"avvo" : "" ,
    	"hi52" : "3,478.01" ,"lo52" : "1,844.09" ,"mc" : "" ,
    	"pe" : "" ,"fwpe" : "" ,"beta" : "" ,"eps" : "" ,
    	"shares" : "" ,"inst_own" : "" ,"name" : "上证综合指数" ,
    	"lname" : "上证指数" ,"type" : "Company" } ]
    */


    GoogStock.prototype.fetchStockCallback = function(data) {
      var result;
      result = {};
      result.status = "fail";
      if (data.length > 0) {
        result.status = "succ";
        result.list = data;
      }
      return this.trigger('fetchFinished', result);
    };

    GoogStock.prototype.fetchRss = function(feedurl) {
      var baseUrl, url,
        _this = this;
      baseUrl = "http://ajax.googleapis.com/ajax/services/feed/load?v=1.0&callback=?&q=";
      feedurl = encodeURIComponent(feedurl);
      url = "" + baseUrl + feedurl + "&num=20&output=json_xml";
      return $.getJSON(url, function(data) {
        return _this.fetchNewsCallback(data);
      });
    };

    GoogStock.prototype.fetchNews = function(stockID) {
      var baseUrl, feedurl, url,
        _this = this;
      baseUrl = "http://ajax.googleapis.com/ajax/services/feed/load?v=1.0&callback=?&q=";
      feedurl = this.getFeedUrl(stockID);
      url = "" + baseUrl + feedurl + "&num=10&output=json_xml";
      return $.getJSON(url, function(data) {
        return _this.fetchNewsCallback(data);
      });
    };

    GoogStock.prototype.getFeedUrl = function(stockID) {
      stockID = this.constructor.canonical(stockID);
      return encodeURIComponent("http://www.google.com.hk/finance/company_news?q=" + stockID + "&ei=M6jdUKCeKoq0kQWH-wE&gl=cn&output=rss");
    };

    GoogStock.prototype.fetchNewsCallback = function(result) {
      if (result.responseStatus === 200) {
        result["status"] = "succ";
      } else {
        result["status"] = "fail";
      }
      return this.trigger('fetchNewsFinished', result);
    };

    return GoogStock;

  })(Spine.Module);

  App["GoogStock"] = GoogStock;

}).call(this);
