// Generated by CoffeeScript 1.4.0
(function() {
  var $, HistoryMoneyPanel,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __slice = [].slice;

  $ = Spine.$;

  HistoryMoneyPanel = (function(_super) {

    __extends(HistoryMoneyPanel, _super);

    HistoryMoneyPanel.prototype.menuItem = {
      menuGroupID: "stockRealTimeGroupID",
      name: "historymoney",
      text: "历史资金流向"
    };

    HistoryMoneyPanel.prototype.elements = {
      'table tbody': 'table'
    };

    HistoryMoneyPanel.prototype.lastQuery = null;

    function HistoryMoneyPanel() {
      this.fetchHistoryMoneyFinished = __bind(this.fetchHistoryMoneyFinished, this);
      HistoryMoneyPanel.__super__.constructor.apply(this, arguments);
      this.bind("refresh", this.fetchData);
      this.ystock = new App.YahooStock();
      this.ystock.bind("fetchHistoryMoneyFinished", this.fetchHistoryMoneyFinished);
    }

    HistoryMoneyPanel.prototype.loadFromTemplate = function() {
      HistoryMoneyPanel.__super__.loadFromTemplate.apply(this, arguments);
      return this.append(window.Tmpls.stockHistoryMoney());
    };

    HistoryMoneyPanel.prototype.activate = function() {
      var args;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      HistoryMoneyPanel.__super__.activate.apply(this, arguments);
      this.table.empty();
      return this.refresh();
    };

    HistoryMoneyPanel.prototype.fetchData = function() {
      if (this.isDataReady()) {
        return this.render();
      } else {
        return this.fetchDataImpl();
      }
    };

    HistoryMoneyPanel.prototype.fetchDataImpl = function() {
      var options;
      this.clearLastQuery();
      this.table.empty();
      Phoniex.Util.appendLoadingBar(this.el);
      options = {};
      options.stockID = this.stack.stockID;
      return this.ystock.fetchHistoryMoney(options);
    };

    HistoryMoneyPanel.prototype.isDataReady = function() {
      if (this.lastQuery != null) {
        return true;
      }
      return false;
    };

    HistoryMoneyPanel.prototype.clearLastQuery = function() {
      return this.lastQuery = null;
    };

    HistoryMoneyPanel.prototype.render = function() {
      Phoniex.Util.removeLoadingBar(this.el);
      if (!this.isDataReady()) {
        return;
      }
      return this.table.append(window.Tmpls.stockHistoryMoneyItem(this.lastQuery));
    };

    HistoryMoneyPanel.prototype.fetchHistoryMoneyFinished = function(result) {
      if (result.status === "fail") {
        Phoniex.Util.removeLoadingBar(this.el);
        return;
      }
      result["color"] = function() {
        if (this.growth.charAt(0) === '-') {
          return "#468847";
        } else {
          return "#FF0000";
        }
      };
      result["netincolor"] = function() {
        if (this.netin.charAt(0) === '-') {
          return "#468847";
        } else {
          return "#FF0000";
        }
      };
      result["largenetincolor"] = function() {
        if (this.largenetin.charAt(0) === '-') {
          return "#468847";
        } else {
          return "#FF0000";
        }
      };
      this.lastQuery = result;
      return this.render();
    };

    HistoryMoneyPanel.prototype.clearCache = function() {
      return this.clearLastQuery();
    };

    return HistoryMoneyPanel;

  })(Phoniex.Panel);

  App["HistoryMoneyPanel"] = HistoryMoneyPanel;

}).call(this);
