// Generated by CoffeeScript 1.4.0
(function() {
  var $, MainController,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  $ = Spine.$;

  MainController = (function(_super) {

    __extends(MainController, _super);

    function MainController() {
      return MainController.__super__.constructor.apply(this, arguments);
    }

    MainController.prototype.className = 'main';

    MainController.prototype["default"] = "stock";

    MainController.prototype.controllers = {
      stock: Stock.StockPage,
      plate: Stock.PlatePage
    };

    return MainController;

  })(Stock.PageStack);

  window.Stock["MainController"] = MainController;

  $(function() {
    return new Stock.MainController({
      el: $("body")
    });
  });

}).call(this);
