// Generated by CoffeeScript 1.4.0
(function() {
  var $, HistoryDealPanel,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __slice = [].slice;

  $ = Spine.$;

  HistoryDealPanel = (function(_super) {

    __extends(HistoryDealPanel, _super);

    HistoryDealPanel.prototype.menuItem = {
      menuGroupID: "stockRealTimeGroupID",
      name: "historydeal",
      text: "历史交易数据"
    };

    HistoryDealPanel.prototype.elements = {
      'table tbody': 'table',
      '#historyDealYear': 'yearSelect',
      '#historyDealSeason': 'seasonSelect'
    };

    HistoryDealPanel.prototype.events = {
      "click #historyDealQuery": "deQuery"
    };

    HistoryDealPanel.prototype.lastQuery = {
      "year": null,
      "season": null,
      "history": null
    };

    function HistoryDealPanel() {
      this.deQuery = __bind(this.deQuery, this);

      this.fetchHistoryDealFinished = __bind(this.fetchHistoryDealFinished, this);
      HistoryDealPanel.__super__.constructor.apply(this, arguments);
      this.bind("refresh", this.fetchData);
      this.ystock = new App.YahooStock();
      this.ystock.bind("fetchHistoryDealFinished", this.fetchHistoryDealFinished);
    }

    HistoryDealPanel.prototype.loadFromTemplate = function() {
      HistoryDealPanel.__super__.loadFromTemplate.apply(this, arguments);
      return this.append(window.Tmpls.stockHistoryDeal());
    };

    HistoryDealPanel.prototype.activate = function() {
      var args;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      HistoryDealPanel.__super__.activate.apply(this, arguments);
      this.table.empty();
      this.initDateSelect();
      return this.refresh();
    };

    HistoryDealPanel.prototype.fetchData = function() {
      if (this.isDataReady()) {
        return this.render();
      } else {
        return this.fetchDataImpl();
      }
    };

    HistoryDealPanel.prototype.initDateSelect = function() {
      var season, year;
      if ((this.lastQuery.year != null) && (this.lastQuery.season != null)) {
        year = this.lastQuery.year;
        season = this.lastQuery.season;
      } else {
        year = "" + (Phoniex.Util.getCurrentYear());
        season = "" + (Phoniex.Util.getCurrentSeason());
      }
      $("option[value=" + year + "]", this.yearSelect).attr('selected', true);
      return $("option[value=" + season + "]", this.seasonSelect).attr('selected', true);
    };

    HistoryDealPanel.prototype.fetchDataImpl = function() {
      var options;
      options = {};
      this.lastQuery.year = options.year = this.yearSelect.val();
      this.lastQuery.season = options.season = this.seasonSelect.val();
      this.lastQuery.history = null;
      options.stockID = this.stack.stockID;
      this.table.empty();
      Phoniex.Util.appendLoadingBar(this.el);
      return this.ystock.fetchHistoryDeal(options);
    };

    HistoryDealPanel.prototype.render = function() {
      Phoniex.Util.removeLoadingBar(this.el);
      if (!this.isDataReady()) {
        return;
      }
      return this.table.append(window.Tmpls.stockHistoryDealItem(this.lastQuery.history));
    };

    HistoryDealPanel.prototype.fetchHistoryDealFinished = function(result) {
      if (result.status === "fail") {
        Phoniex.Util.removeLoadingBar(this.el);
        return;
      }
      result["color"] = function() {
        if (this.growth < 0) {
          return "#468847";
        } else {
          return "#FF0000";
        }
      };
      this.lastQuery.history = result;
      return this.render();
    };

    HistoryDealPanel.prototype.deQuery = function(e) {
      e.preventDefault();
      this.clearCache();
      return this.fetchData();
    };

    HistoryDealPanel.prototype.isDataReady = function() {
      if ((this.lastQuery.year != null) && (this.lastQuery.season != null) && (this.lastQuery.history != null)) {
        return true;
      }
      return false;
    };

    HistoryDealPanel.prototype.clearCache = function() {
      return this.lastQuery.year = this.lastQuery.season = this.lastQuery.history = null;
    };

    return HistoryDealPanel;

  })(Phoniex.Panel);

  App["HistoryDealPanel"] = HistoryDealPanel;

}).call(this);
