// Generated by CoffeeScript 1.4.0
(function() {
  var Spine;

  Spine = this.Spine || require('spine');

  Spine.Model.Local = {
    extended: function() {
      this.change(this.saveLocal);
      return this.fetch(this.loadLocal);
    },
    saveLocal: function() {
      var result;
      console.log("saveLocal dir");
      result = JSON.stringify(this.all());
      return localStorage.setItem(this.className, result);
    },
    loadLocal: function() {
      var result;
      result = localStorage.getItem(this.className);
      if (!result || result === "undefined") {
        result = [];
      }
      return this.refresh(result, {
        clear: true
      });
    }
  };

  if (typeof module !== "undefined" && module !== null) {
    module.exports = Spine.Model.Local;
  }

}).call(this);
