var PhoniexTmpls = (function(window) {
    var partials = {
        "infoModal": function(c,p,i){var _=this;_.b(i=i||"");_.b("<div id=\"promptInfoModal\" class=\"modal hide fade\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"promptInfoModalLabel\" aria-hidden=\"true\">");_.b("\n" + i);_.b("    <div class=\"modal-header\">");_.b("\n" + i);_.b("      <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">×</button>");_.b("\n" + i);_.b("      <h3 id=\"promptInfoModalLabel\">");_.b(_.v(_.f("header",c,p,0)));_.b("</h3>");_.b("\n" + i);_.b("    </div>");_.b("\n" + i);_.b("    <div class=\"modal-body\">");_.b("\n" + i);_.b("      <p>");_.b(_.v(_.f("body",c,p,0)));_.b("</p>");_.b("\n" + i);_.b("    </div>");_.b("\n" + i);_.b("    <div class=\"modal-footer\">");_.b("\n" + i);_.b("      <button class=\"btn btn-primary\" data-dismiss=\"modal\" aria-hidden=\"true\">Close</button>");_.b("\n" + i);_.b("    </div>");_.b("\n" + i);_.b("</div>");return _.fl();;},
        "pagestack": function(c,p,i){var _=this;_.b(i=i||"");_.b("\n" + i);_.b("<div data-role='header'>");_.b("\n" + i);_.b("</div>");_.b("\n" + i);_.b("<div data-role='pagestack'>");_.b("\n" + i);_.b("</div>");_.b("\n" + i);_.b("\n");return _.fl();;},
        "toolbarHeader": function(c,p,i){var _=this;_.b(i=i||"");_.b("<div class=\"navbar  navbar-inverse\" style=\"position: static;\">");_.b("\n" + i);_.b("    <div class=\"navbar-inner\">");_.b("\n" + i);_.b("        <div class=\"container\">");_.b("\n" + i);_.b("            <a class=\"brand\" href=\"#\">title</a>");_.b("\n" + i);_.b("            <div class=\"nav-collapse collapse navbar-inverse-collapse\">");_.b("\n" + i);_.b("                <ul class=\"nav\" data-role=\"mainmenu\">");_.b("\n" + i);_.b("                        <!-- append menuItemTmpl here-->");_.b("\n" + i);_.b("                </ul>");_.b("\n" + i);_.b("                <ul class=\"nav pull-right\">");_.b("\n" + i);_.b("                    <li class=\"divider-vertical\"></li>");_.b("\n" + i);_.b("                    <li><a href=\"#\">Login</a></li>");_.b("\n" + i);_.b("                </ul>");_.b("\n" + i);_.b("\n" + i);_.b("            </div><!-- /.nav-collapse -->");_.b("\n" + i);_.b("        </div>");_.b("\n" + i);_.b("    </div><!-- /navbar-inner -->");_.b("\n" + i);_.b("</div><!-- /navbar -->");_.b("\n" + i);_.b("\n" + i);_.b("\n" + i);_.b("\n");return _.fl();;},
        "pageMenuGroup": function(c,p,i){var _=this;_.b(i=i||"");_.b("<div class=\"accordion-group\">");_.b("\n" + i);_.b("    <div class=\"accordion-heading\">");_.b("\n" + i);_.b("        <a class=\"accordion-toggle\" data-toggle=\"collapse\" data-parent=\"#");_.b(_.v(_.f("pageMenuID",c,p,0)));_.b("\" href=\"#");_.b(_.v(_.f("menuGroupID",c,p,0)));_.b("\">");_.b("\n" + i);_.b("          ");_.b(_.v(_.f("title",c,p,0)));_.b("\n" + i);_.b("        </a>");_.b("\n" + i);_.b("    </div>");_.b("\n" + i);_.b("    <div id=\"");_.b(_.v(_.f("menuGroupID",c,p,0)));_.b("\" class=\"accordion-body collapse in\">");_.b("\n" + i);_.b("        <div class=\"accordion-inner\">");_.b("\n" + i);_.b("            <ul class=\"nav nav-list menu\">");_.b("\n" + i);_.b("            </ul>");_.b("\n" + i);_.b("        </div>");_.b("\n" + i);_.b("    </div>");_.b("\n" + i);_.b("</div>");return _.fl();;},
        "menuItem": function(c,p,i){var _=this;_.b(i=i||"");_.b("<li>");_.b("\n" + i);_.b("    <a href=\"#\" data-name=\"");_.b(_.v(_.f("name",c,p,0)));_.b("\"> ");_.b("\n" + i);if(_.s(_.f("img",c,p,1),c,p,0,56,84,"{{ }}")){_.rs(c,p,function(c,p,_){_.b("    <i class=");_.b(_.v(_.f("img",c,p,0)));_.b(">");_.b("\n");});c.pop();}_.b("    ");_.b(_.v(_.f("text",c,p,0)));_.b("\n" + i);_.b("    </a>");_.b("\n" + i);_.b("</li>");return _.fl();;},
        "selectMenuItem": function(c,p,i){var _=this;_.b(i=i||"");_.b("<option value=");_.b(_.v(_.f("name",c,p,0)));_.b(">");_.b(_.v(_.f("text",c,p,0)));_.b("</option>");return _.fl();;},
        "accordionLeftMenuContent": function(c,p,i){var _=this;_.b(i=i||"");_.b("\n" + i);_.b("<div class=\"row\">");_.b("\n" + i);_.b("    <div class=\"span3\" >");_.b("\n" + i);_.b("        <ul class=\"nav nav-list\" >");_.b("\n" + i);_.b("            <div class=\"accordion\" data-role=\"pagemenu\" id=\"#");_.b(_.v(_.f("pageMenuID",c,p,0)));_.b("\">");_.b("\n" + i);_.b("            </div>");_.b("\n" + i);_.b("        </ul>");_.b("\n" + i);_.b("    </div><!-- row span3-->");_.b("\n" + i);_.b("\n" + i);_.b("    <div class=\"span11\">");_.b("\n" + i);_.b("        <div data-role=\"tophalf\">");_.b("\n" + i);_.b("        </div><!-- /tophalf -->");_.b("\n" + i);_.b("\n" + i);_.b("        <div data-role=\"panels\">");_.b("\n" + i);_.b("        </div>");_.b("\n" + i);_.b("    </div><!-- row span9-->");_.b("\n" + i);_.b("</div> <!-- row-->");_.b("\n");return _.fl();;},
        "comfirmModal": function(c,p,i){var _=this;_.b(i=i||"");_.b("<div id=\"comfirmModal\" class=\"modal hide fade\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"comfirmModalLabel\" aria-hidden=\"true\">");_.b("\n" + i);_.b("    <div class=\"modal-header\">");_.b("\n" + i);_.b("      <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">×</button>");_.b("\n" + i);_.b("      <h3 id=\"comfirmModalLabel\">");_.b(_.v(_.f("header",c,p,0)));_.b("</h3>");_.b("\n" + i);_.b("    </div>");_.b("\n" + i);_.b("    <div class=\"modal-body\">");_.b("\n" + i);_.b("      <p>");_.b(_.v(_.f("body",c,p,0)));_.b("</p>");_.b("\n" + i);_.b("    </div>");_.b("\n" + i);_.b("    <div class=\"modal-footer\">");_.b("\n" + i);_.b("        <button class=\"btn btn-primary\" data-dismiss=\"modal\" aria-hidden=\"true\">Ok</button>");_.b("\n" + i);_.b("        <button class=\"btn\" data-dismiss=\"modal\" aria-hidden=\"true\">Close</button>");_.b("\n" + i);_.b("    </div>");_.b("\n" + i);_.b("</div>");return _.fl();;},
        "panel": function(c,p,i){var _=this;_.b(i=i||"");_.b("<div data-role='panel'> ");_.b("\n" + i);_.b("</div>");_.b("\n" + i);_.b("\n");return _.fl();;},
        "leftMenuContent": function(c,p,i){var _=this;_.b(i=i||"");_.b("\n" + i);_.b("<div class=\"row\">");_.b("\n" + i);_.b("    <div class=\"span3\" >");_.b("\n" + i);_.b("        <div>");_.b("\n" + i);_.b("        <ul class=\"nav nav-list bs-docs-sidenav\" data-role=\"pagemenu\" >");_.b("\n" + i);_.b("        </ul>");_.b("\n" + i);_.b("        </div>");_.b("\n" + i);_.b("    </div><!-- row span3-->");_.b("\n" + i);_.b("\n" + i);_.b("    <div class=\"span11\">");_.b("\n" + i);_.b("        <div data-role=\"tophalf\">");_.b("\n" + i);_.b("        </div><!-- /tophalf -->");_.b("\n" + i);_.b("        <div data-role=\"bottomhalf\">");_.b("\n" + i);_.b("            <div data-role=\"panels\">");_.b("\n" + i);_.b("            </div>");_.b("\n" + i);_.b("        </div><!-- /bottomhalf -->");_.b("\n" + i);_.b("    </div><!-- row span9-->");_.b("\n" + i);_.b("</div> <!-- row-->");_.b("\n");return _.fl();;},
        "page": function(c,p,i){var _=this;_.b(i=i||"");_.b("<div data-role='page'>");_.b("\n" + i);_.b("\n" + i);_.b("    <div data-role='content'>");_.b("\n" + i);_.b("\n" + i);_.b("    </div><!-- content-->");_.b("\n" + i);_.b("\n" + i);_.b("    <div data-role='footer'>");_.b("\n" + i);_.b("    </div><!-- footer-->");_.b("\n" + i);_.b("\n" + i);_.b("</div>");_.b("\n" + i);_.b("\n");return _.fl();;},
        "alert": function(c,p,i){var _=this;_.b(i=i||"");_.b("<div class=\"alert fade in\"><strong>");_.b(_.v(_.f("body",c,p,0)));_.b("</strong></div>");return _.fl();;}
    };

    for (var id in partials) {
        partials[id] = new Hogan.Template(partials[id]);
    }

    var templates = {};
    for (var id in partials) {
        templates[id] = (function(id) {
            return function(context) {
                return partials[id].render(context, partials);
            }
        })(id);
    }
    window.PhoniexTmpls = templates;
    return templates;
})(this);