// Generated by CoffeeScript 1.4.0
(function() {
  var StockList, TagList,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  StockList = (function(_super) {

    __extends(StockList, _super);

    function StockList() {
      return StockList.__super__.constructor.apply(this, arguments);
    }

    StockList.configure("StockList", "stock", "tag");

    StockList.extend(Spine.Model.Local);

    return StockList;

  })(Spine.Model);

  TagList = (function(_super) {

    __extends(TagList, _super);

    function TagList() {
      return TagList.__super__.constructor.apply(this, arguments);
    }

    TagList.configure("TagList", "name");

    TagList.extend(Spine.Model.Local);

    TagList["default"] = {
      name: "Default"
    };

    return TagList;

  })(Spine.Model);

  window.Stock["StockList"] = StockList;

  window.Stock["TagList"] = TagList;

}).call(this);
